-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 22:43:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DoctorDB
-- -----------------------------------------------------
-- This is my Doctor CPSC 471 Databases database. 
DROP SCHEMA IF EXISTS `DoctorDB` ;

-- -----------------------------------------------------
-- Schema DoctorDB
--
-- This is my Doctor CPSC 471 Databases database. 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DoctorDB` ;
USE `DoctorDB` ;

-- -----------------------------------------------------
-- Table `DoctorDB`.`PATIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`PATIENTS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`PATIENTS` (
  `username` VARCHAR(45) NOT NULL,
  `patient_SIN` INT(9) NOT NULL,
  `Health_Card_no` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Fname` VARCHAR(45) NULL,
  `isAdmin` TINYINT NULL DEFAULT 0,
  `City` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `Province` VARCHAR(45) NULL,
  `Insurance Provider` VARCHAR(45) NULL,
  PRIMARY KEY (`username`, `patient_SIN`, `Health_Card_no`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `patient_SIN_UNIQUE` (`patient_SIN` ASC),
  UNIQUE INDEX `Health_Card_no_UNIQUE` (`Health_Card_no` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`MEDICALSTAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`MEDICALSTAFF` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`MEDICALSTAFF` (
  `username` VARCHAR(45) NOT NULL,
  `MedStaff_SIN` INT(9) NOT NULL,
  `password` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Fname` VARCHAR(45) NULL,
  `isAdmin` TINYINT NULL,
  `isSpecialist` TINYINT NULL,
  `isSurgeon` TINYINT NULL,
  PRIMARY KEY (`username`, `MedStaff_SIN`),
  UNIQUE INDEX `MedStaff_SIN_UNIQUE` (`MedStaff_SIN` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`MEDICALINSTITUTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`MEDICALINSTITUTION` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`MEDICALINSTITUTION` (
  `MedInst_ID` INT NOT NULL AUTO_INCREMENT,
  `Inst_Name` VARCHAR(45) NULL,
  `Inst_Location` VARCHAR(45) NULL,
  `Inst_Type` VARCHAR(45) NULL,
  `Opening_Time` VARCHAR(45) NULL COMMENT '//Should be Time(???) ???',
  `Closing_Time` VARCHAR(45) NULL COMMENT '//Should be Time(???) ???',
  PRIMARY KEY (`MedInst_ID`),
  UNIQUE INDEX `idMEDICALINSTITUTION_UNIQUE` (`MedInst_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`SURGEONAREAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`SURGEONAREAS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`SURGEONAREAS` (
  `MedStaff_SIN` INT(9) NOT NULL,
  `Type_of_Surgery` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MedStaff_SIN`, `Type_of_Surgery`),
  INDEX `MedStaff_SIN_idx` (`MedStaff_SIN` ASC),
  CONSTRAINT `MedStaff_SIN`
    FOREIGN KEY (`MedStaff_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`SPECIALISTAREAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`SPECIALISTAREAS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`SPECIALISTAREAS` (
  `MS_SIN` INT(9) NOT NULL,
  `Area_of_Expertice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MS_SIN`, `Area_of_Expertice`),
  INDEX `MS_SIN_idx` (`MS_SIN` ASC),
  CONSTRAINT `MedStaff_SIN`
    FOREIGN KEY (`MS_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`MEDSTAFFQUALIFICATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`MEDSTAFFQUALIFICATIONS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`MEDSTAFFQUALIFICATIONS` (
  `MedStaff_SIN` INT(9) NOT NULL,
  `Qualification` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MedStaff_SIN`, `Qualification`),
  INDEX `MedStaff_SIN_idx` (`MedStaff_SIN` ASC),
  CONSTRAINT `MedStaff_SIN`
    FOREIGN KEY (`MedStaff_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`RECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`RECORD` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`RECORD` (
  `Record_ID` INT NOT NULL AUTO_INCREMENT,
  `Patient_SIN` INT(9) NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Record_ID`, `Patient_SIN`),
  CONSTRAINT `Patient_SIN`
    FOREIGN KEY (`Patient_SIN`)
    REFERENCES `DoctorDB`.`PATIENTS` (`patient_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`PRESCRIPTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`PRESCRIPTION` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`PRESCRIPTION` (
  `Script_ID` INT NOT NULL AUTO_INCREMENT,
  `Patient_SIN` INT(9) NOT NULL,
  `presType` VARCHAR(45) NULL,
  `presName` VARCHAR(45) NULL,
  `length` VARCHAR(45) NULL,
  `Times_Renewable` VARCHAR(45) NULL,
  PRIMARY KEY (`Script_ID`, `Patient_SIN`),
  CONSTRAINT `Patient_SIN`
    FOREIGN KEY (`Patient_SIN`)
    REFERENCES `DoctorDB`.`PATIENTS` (`patient_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`INSURANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`INSURANCE` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`INSURANCE` (
  `Patient_SIN` INT(9) NOT NULL,
  `Item_Covered` VARCHAR(45) NOT NULL,
  `PercentCovered` INT(3) NULL,
  PRIMARY KEY (`Patient_SIN`, `Item_Covered`),
  CONSTRAINT `Patient_SIN`
    FOREIGN KEY (`Patient_SIN`)
    REFERENCES `DoctorDB`.`PATIENTS` (`patient_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`MEDICALHISTORYITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`MEDICALHISTORYITEM` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`MEDICALHISTORYITEM` (
  `Med_Hist_ID` INT NOT NULL AUTO_INCREMENT,
  `Record_ID` INT(9) NOT NULL,
  `Diagnosis` VARCHAR(45) NULL,
  `Recommended_Treatment` VARCHAR(45) NULL,
  `Notes` VARCHAR(1500) NULL,
  PRIMARY KEY (`Med_Hist_ID`, `Record_ID`),
  CONSTRAINT `Record_ID`
    FOREIGN KEY (`Record_ID`)
    REFERENCES `DoctorDB`.`RECORD` (`Record_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`ATTACHMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`ATTACHMENT` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`ATTACHMENT` (
  `Record_ID` INT(9) NOT NULL,
  `DocName` VARCHAR(100) NOT NULL,
  `Type` VARCHAR(10) NULL,
  PRIMARY KEY (`Record_ID`, `DocName`),
  CONSTRAINT `Record_ID`
    FOREIGN KEY (`Record_ID`)
    REFERENCES `DoctorDB`.`RECORD` (`Record_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`MEDHISTSYMPTOMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`MEDHISTSYMPTOMS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`MEDHISTSYMPTOMS` (
  `Med_Hist_ID` INT(9) NOT NULL AUTO_INCREMENT,
  `Symptom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Med_Hist_ID`, `Symptom`),
  CONSTRAINT `Med_Hist_ID`
    FOREIGN KEY (`Med_Hist_ID`)
    REFERENCES `DoctorDB`.`MEDICALHISTORYITEM` (`Med_Hist_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`ACCESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`ACCESS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`ACCESS` (
  `MedStaff_SIN` INT(9) NOT NULL,
  `Record_ID` INT NOT NULL,
  PRIMARY KEY (`MedStaff_SIN`, `Record_ID`),
  INDEX `Record_ID_idx` (`Record_ID` ASC),
  CONSTRAINT `MedStaff_ID`
    FOREIGN KEY (`MedStaff_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Record_ID`
    FOREIGN KEY (`Record_ID`)
    REFERENCES `DoctorDB`.`RECORD` (`Record_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`APPOINTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`APPOINTMENT` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`APPOINTMENT` (
  `ConfirmationNum` INT NOT NULL AUTO_INCREMENT,
  `INST_NAME FOREIGN KEYISNT WORKING` VARCHAR(45) NULL,
  `Inst_Name` VARCHAR(45) NULL,
  `Patient_SIN` INT(9) NULL,
  `MedStaff_SIN` INT(9) NULL,
  `appointmentType` VARCHAR(1500) NULL,
  `Date` DATE NULL,
  `Start_time` DATETIME NULL COMMENT '//time(???)???',
  `End_Time` DATETIME NULL,
  PRIMARY KEY (`ConfirmationNum`),
  INDEX `Patient_SIN_idx` (`Patient_SIN` ASC),
  INDEX `MedStaff_SIN_idx` (`MedStaff_SIN` ASC),
  CONSTRAINT `Patient_SIN`
    FOREIGN KEY (`Patient_SIN`)
    REFERENCES `DoctorDB`.`PATIENTS` (`patient_SIN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MedStaff_SIN`
    FOREIGN KEY (`MedStaff_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Inst_Name`
    FOREIGN KEY (`MedInst_ID`)
    REFERENCES `DoctorDB`.`MEDICALINSTITUTION` (`MedInst_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`WORKPLACEMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`WORKPLACEMENTS` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`WORKPLACEMENTS` (
  `INSTNAME STILL NOT WORKING` VARCHAR(45) NULL,
  `DayWorking` VARCHAR(45) NOT NULL,
  `MedInst_ID` INT NOT NULL,
  `MedStaff_SIN` INT(9) NOT NULL,
  `Inst_name` VARCHAR(45) NULL,
  `workLocationName` VARCHAR(45) NULL COMMENT '...wtf is this attribute supposed to be again?',
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`DayWorking`, `MedInst_ID`, `MedStaff_SIN`),
  INDEX `MedInst_ID_idx` (`MedInst_ID` ASC),
  INDEX `MedStaff_SIN_idx` (`MedStaff_SIN` ASC),
  CONSTRAINT `MedInst_ID`
    FOREIGN KEY (`MedInst_ID`)
    REFERENCES `DoctorDB`.`MEDICALINSTITUTION` (`MedInst_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MedStaff_SIN`
    FOREIGN KEY (`MedStaff_SIN`)
    REFERENCES `DoctorDB`.`MEDICALSTAFF` (`MedStaff_SIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Inst_Name`
    FOREIGN KEY (`MedInst_ID`)
    REFERENCES `DoctorDB`.`MEDICALINSTITUTION` (`MedInst_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DoctorDB`.`DAYSCLOSED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DoctorDB`.`DAYSCLOSED` ;

CREATE TABLE IF NOT EXISTS `DoctorDB`.`DAYSCLOSED` (
  `MedInst_ID` INT(9) NOT NULL,
  `DayClosed` DATE NOT NULL,
  PRIMARY KEY (`MedInst_ID`, `DayClosed`),
  CONSTRAINT `MedInst_ID`
    FOREIGN KEY (`MedInst_ID`)
    REFERENCES `DoctorDB`.`MEDICALINSTITUTION` (`MedInst_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
